import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import Header from "@/components/header";
import Blog from "@/components/blog";
import Subscribe from "@/components/subscribe";
import { headers } from "next/headers";
import Head from "next/head";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

//Add add Meta data here
// Add all analytics data here

const fetchUserProfile = async (hostName: string) => {
  const fetchHostUrl = `http://localhost:3001/api/orchid?username=${hostName}`;
  const data = await fetch(fetchHostUrl);
  return data.json();
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headersList = headers();
  const hostName = headersList.get("X-Forwarded-Host");
  let hostProfile =
    process.env.NODE_ENV === "production" ? hostName?.split(".")[0] : "adrino99";

  const config = await fetchUserProfile(hostProfile as string);
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={`${config.data.profileImageUrl}`} />
        {/* <title>{`${config.data.handle}`}</title>
        <meta name="description" content={`@${config.data.handle} Channel`} /> */}
      </head>
      <body className={inter.className}>
        <Header props={config} />
        {children}
        <Subscribe />
      </body>
    </html>
  );
}
